# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Statusline renderer for Claude Code, Antigravity CLI, and Pi"
  homepage "https://github.com/callmemorgan/claude-statusline"
  version "1.8.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.8.4/claude-statusline_Darwin_x86_64.tar.gz"
      sha256 "4550543769d2774aa5d06168043670c71c4c3f2ffb3a1bbbfca2dce2e3dcd08e"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.8.4/claude-statusline_Darwin_arm64.tar.gz"
      sha256 "feae4cce0aa7fd6b0b4decde749f2ea096cdabf94835cbe28b03343086f9f9c6"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.8.4/claude-statusline_Linux_x86_64.tar.gz"
      sha256 "28f191687ce5cf639291017e8443d7a5fb3c9dec6d1cbe8e86e29409a585c78d"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.8.4/claude-statusline_Linux_arm64.tar.gz"
      sha256 "d36eb3be5e00d38f2df335e80d3b1be203258014fb2599409ed2521cab748771"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  def post_install
    gopath = ENV["GOPATH"] || "#{ENV["HOME"]}/go"
    go_bin = "#{gopath}/bin/claude-statusline"
    if File.exist?(go_bin)
      opoo "Detected another claude-statusline installation at #{go_bin}. Consider removing it to avoid PATH conflicts."
    end

    local_bin = "#{ENV["HOME"]}/.local/bin/claude-statusline"
    if File.exist?(local_bin)
      opoo "Detected another claude-statusline installation at #{local_bin}. Consider removing it to avoid PATH conflicts."
    end
  end

  def caveats
    <<~EOS
      To wire claude-statusline into Claude Code, run:
        claude-statusline install
      Customize anytime with:
        claude-statusline configure
    EOS
  end

  test do
    system "#{bin}/claude-statusline", "--help"
  end
end
