# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Statusline renderer for Claude Code and Antigravity CLI"
  homepage "https://github.com/callmemorgan/claude-statusline"
  version "1.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.5.2/claude-statusline_Darwin_x86_64.tar.gz"
      sha256 "58c742154ee24edd88d2cda169c8b45121d1af700b98b02255b96655556349bd"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.5.2/claude-statusline_Darwin_arm64.tar.gz"
      sha256 "4fa74fd7fe8c732db95b3bf8296c78f81b81120793edeeec55faec29fb362289"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.5.2/claude-statusline_Linux_x86_64.tar.gz"
      sha256 "5453664db5755a4c3d44ed4ba2554b2ecfd448e52a3060cdfc17f76fa6abd3a6"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.5.2/claude-statusline_Linux_arm64.tar.gz"
      sha256 "b0b54f99daba64beae102be46b22d9583b14910ede27f3bd3554dc3f63ea5588"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  def post_install
    gopath = ENV["GOPATH"] || "#{ENV["HOME"]}/go"
    go_bin = "#{gopath}/bin/claude-statusline"
    if File.exist?(go_bin)
      opoo "Detected another claude-statusline installation at #{go_bin}. Consider removing it to avoid PATH conflicts."
    end

    local_bin = "#{ENV["HOME"]}/.local/bin/claude-statusline"
    if File.exist?(local_bin)
      opoo "Detected another claude-statusline installation at #{local_bin}. Consider removing it to avoid PATH conflicts."
    end
  end

  def caveats
    <<~EOS
      To wire claude-statusline into Claude Code, run:
        claude-statusline install
      Customize anytime with:
        claude-statusline configure
    EOS
  end

  test do
    system "#{bin}/claude-statusline", "--help"
  end
end
