# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeStatusline < Formula
  desc "Statusline renderer for Claude Code, Antigravity CLI, and Pi"
  homepage "https://github.com/callmemorgan/claude-statusline"
  version "1.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.7.2/claude-statusline_Darwin_x86_64.tar.gz"
      sha256 "76b450c9aa0564e6d82dff176c8842d2a988fe03c5235679ee1c567f14afcda6"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.7.2/claude-statusline_Darwin_arm64.tar.gz"
      sha256 "6dea21b8fbd9e8c7cfa870e689545e41f9bb2a76977196e4b99f40b76a7c3a3a"

      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.7.2/claude-statusline_Linux_x86_64.tar.gz"
      sha256 "9f1e4ec94b93562666f367ccc1561396437984b6711a71385cc592fc952e70e6"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v1.7.2/claude-statusline_Linux_arm64.tar.gz"
      sha256 "e6e1edf1554bc45d71f92c9f24be8100fb0398eb2b21ad9ca38ae6d806b65859"
      define_method(:install) do
        bin.install "claude-statusline"
      end
    end
  end

  def post_install
    gopath = ENV["GOPATH"] || "#{ENV["HOME"]}/go"
    go_bin = "#{gopath}/bin/claude-statusline"
    if File.exist?(go_bin)
      opoo "Detected another claude-statusline installation at #{go_bin}. Consider removing it to avoid PATH conflicts."
    end

    local_bin = "#{ENV["HOME"]}/.local/bin/claude-statusline"
    if File.exist?(local_bin)
      opoo "Detected another claude-statusline installation at #{local_bin}. Consider removing it to avoid PATH conflicts."
    end
  end

  def caveats
    <<~EOS
      To wire claude-statusline into Claude Code, run:
        claude-statusline install
      Customize anytime with:
        claude-statusline configure
    EOS
  end

  test do
    system "#{bin}/claude-statusline", "--help"
  end
end
