# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-statusline" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "af48c8459d9250ca729bae096982086a6fcc537484c293c04c9ec87b662f13ed"
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v#{version}/claude-statusline_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fffe4693bd6a996f071967d7fae46146551739420c029d98e0c555c98cf69797"
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v#{version}/claude-statusline_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ffbe259ae5fb291b83f883d7f7f5693570e7e7310491efe344e3df7d54bf1709"
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v#{version}/claude-statusline_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "982f26411f756b055ad5ca906fa5c90fb75791a9286e6e75d94309aa0072715d"
      url "https://github.com/callmemorgan/claude-statusline/releases/download/v#{version}/claude-statusline_Linux_arm64.tar.gz"
    end
  end

  name "claude-statusline"
  desc "Statusline renderer for Claude Code, Antigravity CLI, and pi"
  homepage "https://github.com/callmemorgan/claude-statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-statusline"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-statusline"]
    end

    gopath = ENV["GOPATH"] || "#{ENV["HOME"]}/go"
    go_bin = "#{gopath}/bin/claude-statusline"
    if File.exist?(go_bin)
      opoo "Detected another claude-statusline installation at #{go_bin}. Consider removing it to avoid PATH conflicts."
    end

    local_bin = "#{ENV["HOME"]}/.local/bin/claude-statusline"
    if File.exist?(local_bin)
      opoo "Detected another claude-statusline installation at #{local_bin}. Consider removing it to avoid PATH conflicts."
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To wire claude-statusline into Claude Code, run:
      claude-statusline install
    Customize anytime with:
      claude-statusline configure
  EOS
end
